# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('icon_url', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=25, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'app_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'app_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'category_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'developer',
                'managed': False,
            },
        ),
    ]
