# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_googlesimilarapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
