# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_package', models.CharField(max_length=255)),
                ('similar_package', models.CharField(max_length=255)),
                ('distance', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'similar_app',
                'managed': False,
            },
        ),
    ]
