# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-11 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_similarapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.User')),
            ],
            options={
                'db_table': 'user_apps',
                'managed': False,
            },
        ),
    ]
