# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_userapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended_apps',
            field=models.ManyToManyField(to='crawler.App'),
        ),
    ]
